[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
ndarray = "0.16.1"
itertools = "0.13.0"
rayon = "1.10.0"
indicatif = {version = "0.17.9", features = ["rayon"]}
pathfinding = "4.11.0"