name: Typescript

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
    - run: yarn install
      working-directory: 2021
    - run: yarn build
      working-directory: 2021
    - run: yarn test
      working-directory: 2021
